# Usage
#   Start:              docker compose up
#   Stop:               docker compose down
#   Destory:            docker compose down -v

name: aicalendar

services:
  app-web:
    container_name: app-web
    image: teeco123/app-web:test
    ports:
      - 3000:3000
