# Usage
#   Start:              docker compose up
#   Stop:               docker compose down
#   Destory:            docker compose down -v

name: aicalendar

services:
  app-web:
    container_name: app-web
    image: ghcr.io/aicalendar/app-web:dev-latest

  api-user-service:
    container_name: api-user-service
    image: ghcr.io/aicalendar/api-user-service:dev-latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  api-event-service:
    container_name: api-event-service
    image: ghcr.io/aicalendar/api-event-service:dev-latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  nginx:
    container_name: nginx
    image: nginx:1.27.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom Nginx config
    ports:
      - "80:80"

  database:
    container_name: database
    image: postgres:17.3-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.4.2-alpine
    command: >
      sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

volumes:
  database_data:  
